apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
  namespace: ktu-stud-matassp
  labels:
    lab: microservices
spec:
  selector:
    matchLabels:
      app: lab
  replicas: 1
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
        - name: app
          image: mat2s/cloud-lab:v0.1
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          env:
          - name: GITHUB_USERNAME
            value: matassp
